# fly.toml app configuration file generated for research-project-in-hci on 2024-04-22T14:30:07+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'research-project-in-hci'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
